import onnxruntime as ort
import numpy as np
import cv2
import argparse
import sys

sys.path.append("/home/lixin/code/MoGe")
import xml.dom.minidom as xdm
import tqdm


class TSRDetector:
    def __init__(self, onnx_path, device_id=0):
        if ort.get_device() == "cpu":
            print("CPU Device!")
            self.ort_session = ort.InferenceSession(onnx_path)
        else:
            print("GPU Device!")
            self.ort_session = ort.InferenceSession(
                onnx_path,
                providers=["CUDAExecutionProvider"],
                provider_options=[{"device_id": device_id}],
            )
        self.input_size = (1024, 1024)  # 输入的图片大小（做预处理使用
        self.scale = 255  # 图像预处理时的归一化参数
        self.names = [
            "sign_blue_s_roadname",
            "sign_white_n_nomotor",
            "trafficlight",
            "trafficlight_person",
            "sign_yellow_s_electronic_monitoring",
            "sign_blue_s_roadinfo",
            "sign_yellow_s",
            "arrow_l",
            "arrow_ur",
            "electroniceye",
            "sign_white_s_auxiliary",
            "arrow_n_ur",
            "arrow_n_l",
            "sign_yellow_t_crossing",
            "crosswalk_tips",
            "sign_blue_s_crossing",
            "arrow_u",
            "sign_blue_s_public_toilet",
            "sign_green_s_roadinfo",
            "fuzziness",
            "sign_white_n_upspeed_30",
            "sign_blue_n_motorlane",
            "sign_blue_n_bicyclelane",
            "bridge",
            "sign_blue_n_r_lane",
            "sign_red_n_noentry",
            "sign_blue_s_motorlane",
            "sign_blue_n_cararrow_u_motor",
            "sign_green_s_roadinfo_electronic",
            "sign_white_n_upspeed_40",
            "sign_white_n_height_4m",
            "sign_white_n_mixing_limit",
            "sign_white_n_nocar",
            "sign_red_s_pass_lr",
            "sign_blue_n_sailaway",
            "sign_blue_n_cararrow_u_truck",
            "sign_blue_s_roadindication",
            "sign_yellow_s_roadinfo_content",
            "sign_white_n_weight_5t",
            "sign_blue_s",
            "sign_yellow_d_temporary",
            "sign_blue_s_p_motor",
            "sign_yellow_t_temporary",
            "sign_yellow_d_slowly_transit",
            "sign_yellow_t_children",
            "arrow_lu",
            "sign_white_n_noentry_g",
            "arrow_r",
            "sign_white_n_noentry_l_car",
            "sign_blue_n_cararrow_ul_truck",
            "sign_white_n_upspeed_50",
            "sign_white_n_weight_20t",
            "sign_white_n_pedestrianban",
            "sign_white_n_unspeed_30",
            "sign_red_d_stop",
            "sign_blue_n_cararrow_ur_truck",
            "sign_white_n_noentry_r_car",
            "arrow_n_lu",
            "sign_white_n_weight_55t",
            "sign_red_td_rang",
            "sign_white_n_nobicycle",
            "sign_white_s",
            "sign_blue_s_p_bicycle",
            "sign_blue_s_detour",
            "sign_green_s_roadinfo_roadsuperhighway",
            "sign_yellow_t_confluent_r",
            "sign_green_s_indication",
            "sign_green_s_roadinfo_exit",
            "sign_white_n_upspeed_80",
            "sign_green_s",
            "sign_green_s_roadindication",
            "sign_white_s_roadinfo_superhighway",
            "sign_white_n_upspeed_60",
            "sign_blue_s_roadinfo_cartruck",
            "sign_blue_s_roadinfo_car",
            "sign_white_n_weight_49t",
            "sign_white_n_weightr_14t",
            "sign_blue_n_l_lane",
            "sign_blue_s_r_lane",
            "sign_white_n_weight_40t",
            "sign_blue_n_cararrow_l_truck",
            "arrow_n_u",
            "sign_yellow_s_roadinfo",
            "sign_white_n_height_4.3m",
            "arrow_g",
            "sign_white_n_height_2.2m",
            "sign_white_n_nodangercar",
            "sign_white_n_weightr_13t",
            "sign_blue_s_pass_lr",
            "sign_yellow_s_slowdown",
            "sign_blue_n_instruct_r",
            "sign_blue_s_divert_r",
            "arrow_45l",
            "sign_blue_n_nostop",
            "sign_blue_n_cararrow_r_bicycle",
            "sign_white_n_weight_30t",
            "arrow_lg",
            "sign_white_n_nohonking",
            "sign_blue_n_person",
            "sign_yellow_t_intersection_t_right",
            "sign_blue_s_electronic_monitoring",
            "arrow_g_y",
            "sign_yellow_t_danger",
            "sign_red_s_road",
            "sign_blue_s_roadinfo_content",
            "sign_green_s_road",
            "arrow_n_r",
            "sign_white_n_bicyclelane_motor_dotted_line",
            "sign_blue_n_p_bicycle",
            "sign_white_s_provincial_lr",
            "sign_white_s_roadinfo_content",
            "sign_white_n_height_4.8m",
            "sign_white_n_turnround_l",
            "sign_white_n_upspeed_5",
            "sign_yellow_t_tidallane",
            "sign_blue_arrow_roadinfo",
            "sign_white_n_noentry_lr",
            "sign_red_s_travel",
            "sign_blue_n_cararrow_ur_motor",
            "sign_yellow_t_slowly_transit",
            "sign_red_s_pass_r",
            "sign_blue_n_cararrow_ul_motor",
            "sign_green_s_divert_l",
            "sign_white_n_nopass",
            "sign_blue_s_sailaway",
            "sign_black_s_roadinfo_electronic",
            "sign_blue_s_p",
            "sign_white_n_noentry_g_truck",
            "sign_white_n_noentry_ur_truck",
            "sign_blue_s_pedestrian_bridge",
            "sign_yellow_s_roadindication",
            "sign_yellow_s_bicyclelane_person",
            "sign_white_n_height_3m",
            "sign_white_n_height_3.2m",
            "sign_blue_n_cararrow_u_motorcycle",
            "sign_blue_n_cararrow_lr_motor",
            "sign_blue_s_instruct_r",
            "sign_white_s_p",
            "sign_white_n_noentry_r_truck",
            "sign_white_n_noentry_l",
            "sign_yellow_s_detour",
            "sign_blue_n_cararrow_u_bicycle",
            "sign_blue_n_p",
            "arrow_ug",
            "sign_blue_s_inducedarrow",
            "sign_yellow_t_lowhill",
            "sign_yellow_t_narrow_r",
            "sign_white_s_provincial_r",
            "sign_yellow_t_narrow_lr",
            "sign_blue_s_dislocation_track",
            "sign_yellow_t_obstructions_l",
            "sign_white_s_railwayway",
            "sign_yellow_t_overwater",
            "sign_green_d_confluent_r",
            "sign_yellow_t_narrow_bridge",
            "sign_white_td_rang",
            "sign_yellow_t_accident prone",
            "sign_yellow_t_intersection_crossroads",
            "sign_yellow_t_intersection_t_left",
            "sign_yellow_t_crosswind",
            "sign_yellow_t_falling rocks_r",
            "sign_yellow_t_narrow_l",
            "sign_white_s_provincial_tr",
            "sign_yellow_t_railwaycrossing",
            "arrow_lur",
            "arrow_n_lur",
            "sign_white_n_upspeed_20",
            "sign_yellow_t_tunnellights",
            "arrow_n_lr",
            "sign_yellow_t_slippery",
            "sign_white_s_provincial_l",
            "sign_white_s_provincial_u",
            "sign_white_t_railwaycrossing_2",
            "sign_yellow_t_embankment_r",
            "sign_white_t_blackspot",
            "sign_white_t_railwaycrossing_3",
            "sign_white_s_roadname",
            "sign_yellow_t_obstructions_lr",
            "sign_blue_s_disabled",
            "sign_white_n_height_4.5m",
            "sign_yellow_t_turn_r",
            "sign_white_s_electronic_monitoring",
            "sign_yellow_s_fuzziness",
            "sign_blue_n_cararrow_lr_truck",
            "arrow_no",
            "sign_green_s_roadinfo_car",
            "sign_blue_n_downspeed_70",
            "sign_blue_n_downspeed_60",
            "sign_blue_n_downspeed_50",
            "sign_green_s_roadinfo_cartruck",
            "sign_green_s_dislocation_track",
            "sign_green_d_milestones",
            "sign_red_s_divert_r",
            "sign_red_s_divert_l",
            "arrow_45r",
            "sign_white_n_height_4.2m",
            "sign_blue_n_cararrow_ur_car",
            "sign_blue_n_cararrow_u_car",
            "sign_white_s_electroniceye",
            "sign_blue_s_oneway_l",
            "sign_blue_n_instruct_u",
            "sign_blue_n_cararrow_ul_car",
            "sign_blue_n_pass_lr",
            "sign_blue_s_deadend",
            "arrow_n_g_y",
            "sign_blue_n_cararrow_lr_bicycle",
            "sign_blue_n_cararrow_ur_bicycle",
            "sign_blue_s_oneway_u",
            "sign_white_n_noentry_l_bicycle",
            "sign_white_n_noentry_l_truck",
            "sign_blue_n_cararrow_r_motor",
            "sign_white_n_upspeed_35",
            "sign_blue_n_instruct_l",
            "sign_green_s_divert_r",
            "sign_blue_n_cararrow_r_motorcycle",
            "sign_blue_s_deadend_bicycle",
            "sign_blue_s_bicyclelane",
            "sign_red_s_detour",
            "arrow_lr",
            "sign_blue_s_cararrow_lr_motor",
            "sign_white_n_height_3.8m",
            "sign_white_n_p",
            "sign_white_n_height_2.0m",
            "sign_blue_s_divert_l",
            "sign_white_n_height_2.4m",
            "sign_blue_n_deadend_car",
            "sign_white_n_height_3.5m",
            "sign_white_n_height_4.0m",
            "sign_green_s_roadinfo_tollbooths",
            "sign_blue_n_cararrow_ur_motorcycle",
            "sign_white_n_motorlane",
            "arrow_n_g",
            "sign_green_s_roadinfo_distance",
            "sign_white_n_noentry_r",
            "sign_white_n_noentry_u_truck",
            "sign_white_s_roadinfo",
            "sign_yellow_n_slowly_transit",
            "sign_yellow_s_divert_l",
            "sign_yellow_n_bicyclelane_person",
            "sign_yellow_s_bicyclelane",
            "sign_white_n_noparking",
            "sign_blue_s_turnround_l",
            "sign_blue_s_indication",
            "sign_blue_n_cararrow_lr_car",
            "sign_green_s_roadinfo_service",
            "sign_green_s_roadinfo_superhighway",
            "sign_green_s_roadinfo_entersuperhighway",
            "sign_green_s_roadinfo_content",
            "sign_yellow_t_turn_l",
            "arrow_n_gr",
            "sign_yellow_s_oneway_l",
            "sign_white_n_height_1.8m",
            "sign_white_n_p_bicycle",
            "sign_blue_n_cararrow_ul_bicycle",
            "sign_white_s_public_toilet",
            "sign_white_n_weight_15t",
            "sign_white_n_upspeed_55",
            "sign_yellow_t_reverse_turn",
            "sign_white_n_height_5m",
            "sign_yellow_s_roadinfo_tollbooths",
            "sign_green_s_roadinfo_emergency",
            "sign_white_n_upspeed_120",
            "sign_blue_n_downspeed_110",
            "sign_blue_n_downspeed_90",
            "sign_green_s_roadname",
            "sign_blue_d_confluent_r",
            "sign_white_n_weightr_10t",
            "sign_red_s_slowdown",
            "sign_white_n_weight_10t",
            "sign_white_n_noentry_g_car",
            "sign_blue_s_oneway_r",
            "sign_white_n_slowly_transit",
            "sign_blue_n_bicyclelane_person",
            "sign_white_n_height_6.2m",
            "arrow_n_45l",
            "sign_blue_s_roadinfo_electronic",
            "sign_red_arrow_roadinfo",
            "sign_white_n_noentry_u_car",
            "sign_white_n_height_5.2m",
            "sign_blue_n_cararrow_l_bicycle",
            "sign_yellow_t_twoway",
            "sign_white_n_unspeed_40",
            "sign_white_t_electroniceye",
            "sign_white_n_noentry_u",
            "sign_black_s_roadinfo",
            "sign_blue_s_roadinfo_superhighway",
            "sign_white_n_height_2.5m",
            "sign_green_s_electroniceye",
            "sign_blue_n_downspeed_80",
            "sign_white_n_upspeed_100",
            "sign_blue_n_instruct_lr",
            "sign_yellow_s_divert_r",
            "sign_white_n_height_2m",
            "sign_blue_d_milestones",
            "sign_blue_n_turnround_l",
            "sign_white_n_noentry",
            "sign_blue_s_roadinfo_motor",
            "sign_white_n_height_5.5m",
            "sign_blue_n_instruct_ur",
            "arrow_special",
            "sign_green_s_p",
            "sign_blue_s_lr_lane",
            "sign_white_n_upspeed_15",
            "sign_green_n_p_motor",
            "sign_green_s_electronic_monitoring",
            "sign_white_s_slowdown",
            "sign_white_arrow_roadinfo",
            "sign_blue_n_lr_lane",
            "sign_blue_d_temporary",
            "sign_yellow_s_electroniceye",
            "sign_blue_d_shunt_r",
            "sign_white_s_road",
            "sign_green_n_lr_lane",
            "sign_white_n_upspeed_70",
            "sign_green_s_roadinfo_motor",
            "sign_white_n_noovertaking",
            "sign_yellow_t_confluent_l",
            "sign_yellow_t_intersection_y_merge",
            "sign_white_n_height_5.0m",
            "sign_white_t_intersection_t_right",
            "sign_green_n_p",
            "sign_blue_n_instruct_lur",
            "arrow_n_ug",
            "sign_yellow_t_lowlyingroad",
            "sign_whtie_s_roadname",
            "sign_yellow_t_mountain_l",
            "sign_yellow_d_shunt_r",
            "sign_yellow_t_mountain_r",
            "sign_blue_n_turnround_r",
            "sign_white_n_weight_25t",
            "_yellow_t_slowly_transit",
            "sign_blue_s_slowdown",
            "sign_yellow_t_ferries",
            "sign_green_d_confluent_l",
            "sign_yellow_t_roundabout",
            "sign_blue_d_shunt_l",
            "sign_yellow_t_falling rocks_l",
            "sign_yellow_t_railwayperson",
            "sign_yellow_t_humpbridge",
            "sign_blue_n_roundabout",
            "sign_blue_s_roadinfo_exit",
            "sign_white_s_roadinfo_distance",
            "sign_white_n_unspeed_60",
            "sign_yellow_s_pass_lr",
            "sign_yellow_s_upspeed_20",
            "sign_green_s_roadinfo_truck",
            "sign_green_d_shunt_r",
            "sign_red_s",
            "sign_yellow_s_person",
            "sign_green_s_lr_lane",
            "sign_red_n_pass_l",
            "sign_red_n_pass_r",
            "sign_white_n_nolong_stop",
            "arrow_n_ul",
            "sign_yellow_t_intersection_right",
            "sign_yellow_s_roadinfo_distance",
            "sign_green_s_bicyclelane",
            "sign_white_d_shunt_r",
            "sign_white_n_notwocar",
            "sign_yellow_s_upspeed_80",
            "sign_yellow_n_upspeed_40",
            "sign_blue_s_l_lane",
            "sign_white_t_children",
            "sign_yellow_s__roadinfo_distance",
            "sign_green_s_motorlane_cartruck",
            "sign_green_s_motorlane",
            "sign_blue_n_flyover",
            "sign_yellow_t_intersection_y",
            "sign_white_s_arrow_roadinfo",
            "sign_white_n_width_3.5m",
            "sign_yellow_t_embankment_l",
            "sign_yellow_t_bumpyroad",
            "sign_yellow_t_roughroad",
            "sign_yellow_t_livestock",
            "sign_white_n_weightr_7t",
            "sign_white_n_danger_bridge",
            "sign_blue_d_confluent_l",
            "sign_white_t_danger",
            "sign_white_n_chinese",
            "sign_yellow_s_auxiliary",
            "sign_blue_s_signage",
            "sign_yellow_t_villages",
            "sign_yellow_t_intersection",
            "sign_white_n_nobicycle_downhill",
            "sign_white_s_detour",
            "sign_white_s_railwayperson",
            "sign_red_n_upspeed_5",
            "sign_blue_s_electroniceye",
            "sign_red_s_roadinfo",
            "sign_yellow_t_intersection_t",
            "sign_yellow_s_road",
            "sign_yellow_t_shunt_l",
            "sign_blue_n_instruct_ul",
            "sign_red_t_accident prone",
            "sign_white_s_roadinfo_exit",
            "sign_yellow_n_nomotor",
            "sign_yellow_s_children",
            "sign_white_n_unspeed_50",
            "sign_blue_n_crossing",
            "sign_yellow_t_electroniceye",
            "sign_white_n_accident prone",
            "sign_yellow_t_bicyclelane",
            "sign_white_n_weight_50t",
            "sign_red_s_p",
            "sign_yellow_td_intersection_t_right",
            "sign_yellow_td_intersection_crossroads",
            "sign_yellow_td_intersection_t",
            "sign_yellow_td_intersection_t_left",
            "sign_white_n_noentry_lr_truck",
            "arrow_n_lg",
            "sign_blue_n_cararrow_lr_motorcycle",
            "sign_blue_s_roadinfo_largecar",
            "sign_yellow_s_crossing",
            "sign_blue_s_roadinfo_distance",
            "sign_yellow_s_electronic",
            "r",
            "sign_white_s_indication",
            "sign_green_s_roadinfo_largecar",
            "sign_white_n_width_3m",
            "sign_yellow_s_upspeed_5",
            "sign_white_s_roadinfo_car",
            "sign_white_s_roadinfo_cartruck",
            "sign_green_s_slowdown",
            "sign_black_n_upspeed_60",
            "sign_green_s_confluent_r",
            "sign_red_s_pass_l",
            "sign_white _s_tunnellights",
            "sign_blue_s_tunnellights",
            "sign_blue_n_p_motor",
            "sign_blue_n_cararrow_l_motorcycle",
            "sign_white_n_height_2.1m",
            "sign_red_s_slowly_transit",
        ]

        def pre_process(self, img):
            print("pre_process image size:", img.shape)
            img = cv2.resize(img, self.input_size)
            # img = img[:, :, ::-1]
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # BGR to RGB

            img = np.ascontiguousarray(
                np.transpose(img, (2, 0, 1))
            )  # 将图像从HWC转为CHW
            img = img / self.scale
            img = img[None]  # CHW to 1CHW 添加了一个批维度
            return img

        def detect(self, img, conf_thres=0.25, iou_thres=0.45, max_det=300):
            img = img.astype(np.float32)
            h, w, c = img.shape
            processed_img = self.pre_process(img)
            ort_img_input = {self.ort_session.get_inputs()[0].name:pre_process}
            ort_img_out = self.ort_session.run(None, ort_img_input)[0]
            
            
if __name__ = "__main__":
    model = TSRDetector()
            
